
""" 
Plot the spatial resolutions of Confocal,STED and SPLIT-STED images from the .csv file generated by
SPLIT-STED_CWF_multiSTEDpercent_Metrics.py
or
SPLIT-STED_Median_multiSTEDpercent_Metrics
"""

import os
import glob

import numpy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn
import easygui
import itertools
from sys import path as path1; 
Functionspath=os.path.join(os.path.dirname(os.path.dirname(__file__)), "Functions")
path1.append(Functionspath)
from statistics_functions import get_significance
import scipy

matplotlib.rcParams['axes.linewidth'] = 0.8

# Ask user name of the folder where the plots will be saved and create it
savefoldername =str(input("Name of folder: "))
savefolder=os.path.join(os.path.expanduser("~/Desktop"),savefoldername + "_PhasorDists")
os.makedirs(savefolder,exist_ok=True)

#Path to folder containing the .csv files
csvpaths = easygui.fileopenbox(default=os.path.expanduser("~/Desktop"),multiple=True)



powers=["_*","_10","_20","_30","_40"]
powersnum=[0,10,20,30,40]
ticklabels=["0","44","88","132","176"]

colors=["#7ce8ffff","#55d0ffff","#00acdfff","#0080bfff","#00456bff"]

# Read the .csv files and concatenate them
cumdf=[]
csvfull=[]
# Make a figure for each metric
fig1,ax1=plt.subplots(figsize=(8,6))
fig2,ax2=plt.subplots(figsize=(8,6))
fig3,ax3=plt.subplots(figsize=(8,6))
fig4,ax4=plt.subplots(ncols=len(csvpaths),figsize=(8,6))
for i,csvpath in enumerate(csvpaths):
    Overall_data= pd.read_csv(csvpath)
    print(Overall_data.shape)
    print(list(Overall_data.columns))


    pdf = Overall_data.melt(id_vars=['STEDpercent'], value_vars=['Res sted stack', 'Res splitsted'], var_name='measure', value_name='value')
    
    #seaborn.violinplot(data=pdf, x="STEDpercent", y="value", hue="measure", split=True, ax=ax4[i])
    #seaborn.stripplot(data=pdf, x="STEDpercent", y="value", hue="measure", dodge=True,  jitter=False,ax=ax4[i])
    seaborn.pointplot(data=pdf, x="STEDpercent", y="value", hue="measure", ax=ax4[i])
    ax4[i].set_title(os.path.basename(csvpath).split("objectifs_")[1].split(".csv")[0])

    ax4[i].set_ylabel("Resolution [nm]")
    ax4[i].set_xlabel("Depletion Power [mW]")
    ax4[i].set_ylim(3,10)


    ax4[i].set_yticks([4,5,6,7,8,9,10])
    ax4[i].set_yticklabels([80,100,120,140,160,180,200])



    MeanDF=Overall_data.groupby('STEDpercent').mean(numeric_only=True).reset_index()
    Meanconf=Overall_data[ 'Res conf stack'].mean()
    res=numpy.array(MeanDF[ 'Res sted stack']*20)
    res=numpy.insert(res,0,Meanconf*20)

    ressplit=numpy.array(MeanDF[ 'Res splitsted']*20)
    ressplit=numpy.insert(ressplit,0,Meanconf*20)

    pows=numpy.array(MeanDF["STEDpercent"])
    pows=numpy.insert(pows,0,0)


    print(MeanDF["STEDpercent"])
    ax1.plot(pows,res,"o-",label=os.path.basename(csvpath).split("objectifs_")[1].split(".csv")[0])
    ax2.plot(pows,res,"o-",alpha=0.5,label=os.path.basename(csvpath).split("objectifs_")[1].split(".csv")[0])
    ax2.plot(pows,ressplit,"o-",label=os.path.basename(csvpath).split("objectifs_")[1].split(".csv")[0])
    ax3.plot(MeanDF["STEDpercent"],(MeanDF[ 'Res sted stack']-MeanDF['Res splitsted'])/MeanDF[ 'Res sted stack'],"o-",label=os.path.basename(csvpath).split("objectifs_")[1].split(".csv")[0])
ax1.set_ylabel("Resolution STED[nm]")
ax1.set_xlabel("Depletion Power [mW]")
ax1.legend(frameon=False, fontsize=8)
ax1.set_xticks(powersnum)
ax1.set_xticklabels(ticklabels)
ax2.set_ylabel("Resolution SPLIT-STED[nm]")
ax2.set_xlabel("Depletion Power [mW]")
ax2.legend(frameon=False, fontsize=8)
ax3.legend(frameon=False, fontsize=8)
ax2.set_xticks(powersnum)
ax2.set_xticklabels(ticklabels)

ax3.set_xticks(powersnum)
ax3.set_xticklabels(ticklabels)
ax3.set_ylabel("Resolution improvement with SPLIT-STED [%]")
ax3.set_xlabel("Depletion Power [mW]")
plt.show()
fig2.savefig(os.path.join(savefolder,"SPLIT_Resolution.pdf"))
fig1.savefig(os.path.join(savefolder,"STED_Resolution.pdf"))
fig3.savefig(os.path.join(savefolder,"Resolution_Comparison.pdf"))
fig4.savefig(os.path.join(savefolder,"Resolution_Comparison_strip.pdf"))