
""" 
Plot the metrics of distances between the phasors from the .csv file generated by
PhasorDistribution_STED_EllipseFit_2Species.py
"""

import os
import glob

import numpy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn
import easygui
import itertools
from sys import path as path1; 
Functionspath=os.path.join(os.path.dirname(os.path.dirname(__file__)), "Functions")
path1.append(Functionspath)
from statistics_functions import get_significance
import scipy

matplotlib.rcParams['axes.linewidth'] = 0.8

fig,ax=plt.subplots(figsize=(3,1))
lambdas=[3,5,7]
for l in lambdas:
    noisegrid=numpy.random.poisson(lam=l, size=10000).astype(int)
    ax.hist(noisegrid, bins=21, range=(0, 20),histtype='step',density=True, fill=False, label=f'λ={l}')
ax.legend()
#plt.show()    
ax.set_xlabel('Photon Count')
ax.set_ylabel('Frequency')



# Ask user name of the folder where the plots will be saved and create it
savefoldername =str(input("Name of folder: "))
savefolder=os.path.join(os.path.expanduser("~/Desktop"),savefoldername + "_Simulation_Noise")
os.makedirs(savefolder,exist_ok=True)

#Path to folder containing the .csv files
#csvpath = easygui.fileopenbox(default=os.path.expanduser("~/Desktop"),multiple=False)
folder=easygui.diropenbox(default=os.path.expanduser("~/Desktop"))
folders=[folder]



colors=[["#7ce8ffff","#55d0ffff","#00acdfff","#2895cbff","#1676a9ff","#00456bff"],["#fcbcd7ff","#f9a3cbff","#ef87beff","#e569b3ff","#bf4290ff","#5d1a43ff","#981164ff"]]

# Read the .csv files and concatenate them
cumdf=[]
csvfull=[]
# Loop over the folders containing the CSV files and pool the data into a single dataframe.
for i,folder in enumerate(folders):

    csvlist=glob.glob(os.path.join(folder,"*.csv"))
    print(csvlist)


    Overall_data= pd.concat(map(pd.read_csv, csvlist))
    cumdf.append(Overall_data)

    print(Overall_data.shape)
    print(list(Overall_data.columns))
    print(Overall_data)

Overall_data.dropna(axis=0, how='all', inplace=True)
for path in Overall_data["image1"]:
  
    Overall_data["image1"]= os.path.basename(path)
for path in Overall_data["image2"]:
    Overall_data["image2"]= os.path.basename(path)

#Overall_data= pd.read_csv(csvpath)
#print(Overall_data.shape)
print(list(Overall_data.columns))

df=Overall_data[Overall_data["Noise type"]=="Uniform"]
df=df[df["Noise number photons"]==0]

dfcontrol=df.copy()
powersC=numpy.unique(df["Power"])
print(powersC)
ForePreC=numpy.array(df[["Foreground_int"]])
BackPreC=numpy.array(df[["Background_int"]])
ForePostC=numpy.array(df[["Foreground_int_post"]])
BackPostC=numpy.array(df[["Background_int_post"]])
PowC=numpy.array(df[["Power"]])

dfmean=df.groupby("Power")[ ['Power', 'Foreground_int', 'Background_int', 'Foreground_int_post', 'Background_int_post']].mean(numeric_only=True)
dfstd=df.groupby("Power")[ ['Power',  'Foreground_int', 'Background_int', 'Foreground_int_post', 'Background_int_post']].sem(numeric_only=True)

print(dfmean)
print(dfstd)

types=["Uniform","IRF","Alexa647"]
fig2,ax2=plt.subplots(ncols=3,nrows=2,sharex=True,sharey='row',figsize=(10,6))
for t,type in enumerate(types):
    fig3,ax3=plt.subplots(ncols=1,nrows=2,sharex=True,sharey=False,figsize=(4,8))
    #fig1,ax1=plt.subplots(figsize=(8,6))
    df=Overall_data[Overall_data["Noise type"]==type]
    pixels=numpy.unique(df["Noise percent pixels"])
    photons=numpy.unique(df["Noise number photons"])
    print(type)
    print(pixels)
    print(photons)
    if 0 in pixels and t<3:
        print("Removing 0 from pixels")
        pixels=numpy.delete(pixels,numpy.where(pixels==0)[0][0])
    print(pixels)
    if 0 in photons and t<3:
        print("Removing 0 from photons")
        photons=numpy.delete(photons,numpy.where(photons==0)[0][0])
    print(photons)
   
    for i,p in enumerate(pixels):
        if p==0 and t<3:
            continue
        df2=df[df["Noise percent pixels"]==p]


        ax3[0].errorbar(powersC,dfmean['Foreground_int'],yerr=dfstd["Foreground_int"],c="k",fmt="o", label="Foreground original image",ecolor="k", capsize=5, elinewidth=0.8, ms=5)
        ax3[1].errorbar(powersC,dfmean["Background_int"],yerr=dfstd["Background_int"],c="grey", fmt="o", label="Background original image",ecolor="grey", capsize=5, elinewidth=0.8, ms=5)
        ax2[0,t].errorbar(powersC,dfmean['Foreground_int'],yerr=dfstd["Foreground_int"],c="k",fmt="o", label="Foreground original image",ecolor="k", capsize=5, elinewidth=0.8, ms=5)
        ax2[1,t].errorbar(powersC,dfmean["Background_int"],yerr=dfstd["Background_int"],c="grey", fmt="o", label="Background original image",ecolor="grey", capsize=5, elinewidth=0.8, ms=5)



        for j,n in enumerate(photons):

            df3=df2[df2["Noise number photons"]==n]
            powers=numpy.unique(df3["Power"])
            print(powers)



            df3mean=df3.groupby("Power")[ ['Power', 'Foreground_int', 'Background_int', 'Foreground_int_post', 'Background_int_post']].mean(numeric_only=True)
            df3std=df3.groupby("Power")[ ['Power', 'Foreground_int', 'Background_int', 'Foreground_int_post', 'Background_int_post']].sem(numeric_only=True)

      
            #ax3[0].errorbar(powers,df3mean["Foreground_int"],yerr=df3std["Foreground_int"],fmt="o",c="gold", label="λ={} Foreground Pre".format(n),ecolor="gold", capsize=5, elinewidth=0.8, ms=5)
            #ax3[1].errorbar(powers,df3mean["Background_int"],yerr=df3std["Background_int"],fmt="o",c="gold", label="λ={} Background Pre".format(n),ecolor="gold", capsize=5, elinewidth=0.8, ms=5)
            ax3[1].errorbar(powers,df3mean["Background_int_post"],yerr=df3std["Background_int_post"],fmt="o",c=colors[1][j], label="λ={} Background".format(n),ecolor=colors[1][j], capsize=5, elinewidth=0.8, ms=5)
            ax3[0].errorbar(powers,df3mean["Foreground_int_post"],yerr=df3std["Foreground_int_post"],fmt="o",c=colors[0][j], label="λ={} Foreground".format(n),ecolor=colors[0][j], capsize=5, elinewidth=0.8, ms=5)
            ax3[1].errorbar(powers,df3mean["Background_int_post"],yerr=df3std["Background_int_post"],fmt="o",c=colors[1][j], label="λ={} Background".format(n),ecolor=colors[1][j], capsize=5, elinewidth=0.8, ms=5)
            ax2[0,t].errorbar(powers,df3mean["Foreground_int_post"],yerr=df3std["Foreground_int_post"],fmt="o",c=colors[0][j], label="λ={} Foreground".format(n),ecolor=colors[0][j], capsize=5, elinewidth=0.8, ms=5)
            ax2[1,t].errorbar(powers,df3mean["Background_int_post"],yerr=df3std["Background_int_post"],fmt="o",c=colors[1][j], label="λ={} Background".format(n),ecolor=colors[1][j], capsize=5, elinewidth=0.8, ms=5)


        ax2[0,t].set_title("{}".format(type))
        ax2[0,t].set_xlim([5,45])
        ax2[1,t].set_xlim([5,45])
        #if t<2:
        #    ax2[t,i].set_xticklabels([])
        #if i>0:
        #    ax2[t,i].set_yticklabels([])
        ax3[i].set_title("{}".format(type))
        ax2[1,t].set_xlabel("Power")
        ax2[0,0].set_ylabel("Mean of Foreground Intensity")
        ax2[1,0].set_ylabel("Mean of Background Intensity")
        ax3[1].set_xlim([5,45])
        ax3[0].set_xlim([5,45])
        ax3[0].set_xlabel("Power")
        ax3[0].set_ylabel("Mean of Foreground Intensity")
        ax3[1].set_xlabel("Power")
        ax3[1].set_ylabel("Mean of Background Intensity")
        ax3[0].legend(frameon=False)
        ax3[1].legend(frameon=False)
        ax2[0,1].legend(frameon=False,loc='upper right')
        ax2[1,1].legend(frameon=False,loc='upper right')

    fig3.savefig(os.path.join(savefolder,"Intensity_{}.pdf".format(type)),transparent=True, bbox_inches='tight')
fig2.subplots_adjust(wspace=0,hspace=0)
fig2.savefig(os.path.join(savefolder,"Intensity_All.pdf"),transparent=True, bbox_inches='tight')
#fig.savefig(os.path.join(savefolder,"Poisson_Dists.pdf"),transparent=True, bbox_inches='tight')
plt.show()
