
""" 
Plot the metrics of distances between the phasors from the .csv file generated by
PhasorDistribution_STED_EllipseFit_2Species.py
"""

import os
import glob

import numpy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn
import easygui
import itertools
from sys import path as path1; 
Functionspath=os.path.join(os.path.dirname(os.path.dirname(__file__)), "Functions")
path1.append(Functionspath)
from statistics_functions import get_significance
import scipy

matplotlib.rcParams['axes.linewidth'] = 0.8

# Ask user name of the folder where the plots will be saved and create it
savefoldername =str(input("Name of folder: "))
savefolder=os.path.join(os.path.expanduser("~/Desktop"),savefoldername + "_TriangleIOU_Noise")
os.makedirs(savefolder,exist_ok=True)

#Path to folder containing the .csv files
csvpath = easygui.fileopenbox(default=os.path.expanduser("~/Desktop"),multiple=False)



colors=["#7ce8ffff","#55d0ffff","#00acdfff","#2895cbff","#1676a9ff","#00456bff"]

# Read the .csv files and concatenate them
cumdf=[]
csvfull=[]



Overall_data= pd.read_csv(csvpath)
print(Overall_data.shape)
print(list(Overall_data.columns))

df=Overall_data[Overall_data["Noise type"]=="Uniform"]
df=df[df["Noise number photons"]==0]

P1C=numpy.array(df[["P1_x","P1_y"]])
P2C=numpy.array(df[["P2_x","P2_y"]])
P3C=numpy.array(df[["P3_x","P3_y"]])

print(P1C)
print(P2C)
print(P3C)

types=["Uniform","IRF","Alexa647"]
fig2,ax2=plt.subplots(ncols=7,nrows=3,sharex=True,sharey=True,figsize=(27,9))
for t,type in enumerate(types):
    fig1,ax1=plt.subplots(figsize=(8,6))
    df=Overall_data[Overall_data["Noise type"]==type]
    pixels=numpy.unique(df["Noise percent pixels"])
    photons=numpy.unique(df["Noise number photons"])
    print(pixels)
    print(photons)
    if 0 in pixels:
        pixels=numpy.delete(pixels,numpy.where(pixels==0)[0][0])
    print(pixels)
    if 0 in photons:
        photons=numpy.delete(photons,numpy.where(photons==0)[0][0])
    print(photons)
    for i,p in enumerate(photons):
        if p==0:
            continue
        df2=df[df["Noise number photons"]==p]
        ious=numpy.array(df2["IoU"])
        pixelss=numpy.array(df2["Noise percent pixels"])
        
        ious=numpy.insert(ious,0,1)
        pixelss=numpy.insert(pixelss,0,0)

        ax1.plot(pixelss,ious,"o-", label="{}photons, {}".format(p,type))
    ax1.set_ylabel("Intersection over Union (IoU)")
    ax1.set_xlabel("Percent of pixels with noise [%]")
    ax1.legend(frameon=False, fontsize=8)

    fig1.savefig(os.path.join(savefolder,"TriangleIOU_{}.pdf".format(type)),transparent=True, bbox_inches='tight')



    
        # draw universal semi-circle
    edge = numpy.linspace(start=0, stop=15, num=200)
    theta = numpy.linspace(0, numpy.pi, 100)
    r = 0.5
    x1 = r * numpy.cos(theta) + 0.5
    x2 = r * numpy.sin(theta)
    
    for i,p in enumerate(pixels):
        if p==0:
            continue
        df2=df[df["Noise percent pixels"]==p]
        ax2[t,i].plot(x1, x2, color="k", ls="--",linewidth=0.8)
        ax2[t,i].plot([P1C[0][0],P2C[0][0]],[P1C[0][1],P2C[0][1]],"o-",c="black",label="No Background added")
        ax2[t,i].plot([P2C[0][0],P3C[0][0]],[P2C[0][1],P3C[0][1]],"o-",c="black")
        ax2[t,i].plot([P1C[0][0],P3C[0][0]],[P1C[0][1],P3C[0][1]],"o-",c="black")
        for j,n in enumerate(photons):

            df3=df2[df2["Noise number photons"]==n]
            ax2[t,i].plot([df3["P1_x"],df3["P2_x"]],[df3["P1_y"],df3["P2_y"]],"o-",c=colors[j], label="{} photons".format(n))
            ax2[t,i].plot([df3["P2_x"],df3["P3_x"]],[df3["P2_y"],df3["P3_y"]],"o-",c=colors[j])
            ax2[t,i].plot([df3["P1_x"],df3["P3_x"]],[df3["P1_y"],df3["P3_y"]],"o-",c=colors[j])

        ax2[t,i].set_title("{}:{}% pixels".format(type,p))
        ax2[t,i].set_ylabel("S")
        ax2[t,i].set_xlabel("G")
        ax2[t,i].set_xlim(0,1)
        ax2[t,i].set_ylim(0,0.8)
ax2[2,6].legend(frameon=False, fontsize=8)
fig2.savefig(os.path.join(savefolder,"Triangledraw_{}.pdf".format(type)),transparent=True, bbox_inches='tight')
plt.show()
