
""" 
Calculates the displacement between the phasors of STED images of a dye acquired with different depletion powers along a line
 from the .csv file generated by PhasorDistribution_STED_EllipseFit_2Species.py
"""

import os
import glob

import numpy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn
import easygui
import itertools
from sys import path as path1; 
Functionspath=os.path.join(os.path.dirname(os.path.dirname(__file__)), "Functions")
path1.append(Functionspath)
from statistics_functions import get_significance
import scipy

matplotlib.rcParams['axes.linewidth'] = 0.8

# Ask user name of the folder where the plots will be saved and create it
savefoldername =str(input("Name of folder: "))
savefolder=os.path.join(os.path.expanduser("~/Desktop"),savefoldername + "_PhasorDists")
os.makedirs(savefolder,exist_ok=True)

#Path to folder containing the .csv files
csvpaths = easygui.fileopenbox(default=os.path.expanduser("~/Desktop"),multiple=True)



powers=["_*","_10","_20","_30","_40"]
powersnum=[0,10,20,30,40]
ticklabels=["0","44","88","132","176"]

colors=["#7ce8ffff","#55d0ffff","#00acdfff","#0080bfff","#00456bff"]

# Read the .csv files and concatenate them
cumdf=[]
csvfull=[]
# Make a figure for each metric
fig1,ax1=plt.subplots(figsize=(8,6))
fig2,ax2=plt.subplots(figsize=(8,6))
for i,csvpath in enumerate(csvpaths):
    Overall_data= pd.read_csv(csvpath,header=None, names=['Power', 'CentroidX', 'CentroidY'])
    print(Overall_data.shape)
    print(list(Overall_data.columns))



    MeanDF=Overall_data.groupby('Power').mean().reset_index()
    print(MeanDF)

    #maxpower=MeanDF["Power"].max()
    maxpower=30
    p3=numpy.array(MeanDF[["CentroidX","CentroidY"]])
    P_n=numpy.array([MeanDF.loc[(MeanDF["Power"] ==maxpower), 'CentroidX'] ,MeanDF.loc[(MeanDF["Power"] ==maxpower), 'CentroidY'] ])
    p2=numpy.array([MeanDF.loc[(MeanDF["Power"] ==0), 'CentroidX'] ,MeanDF.loc[(MeanDF["Power"] ==0), 'CentroidY'] ])
    #distance between pn and p2
    l= numpy.sum((P_n - p2)**2)
    var=P_n-p2
    #Projection of mixed phasor onto line
    t=numpy.sum(((numpy.transpose(p3) - p2) * (P_n - p2)), axis=0)
    tnorm=numpy.sum(((numpy.transpose(p3) - p2) * (P_n - p2)) / l, axis=0)
    print(t)
    print(MeanDF["Power"])
    ax1.plot(MeanDF["Power"],t,"o-",label=os.path.basename(csvpath).split("EllipsePositions_")[1].split(".csv")[0])
    ax2.plot(MeanDF["Power"],tnorm,"o-",label=os.path.basename(csvpath).split("EllipsePositions_")[1].split(".csv")[0])
ax1.set_ylabel("Cumulative displacement")
ax1.set_xlabel("Depletion Power [mW]")
ax1.legend(frameon=False, fontsize=8)
ax1.set_xticks(powersnum)
ax1.set_xticklabels(ticklabels)
ax2.set_ylabel("Cumulative displacement")
ax2.set_xlabel("Depletion Power [mW]")
ax2.legend(frameon=False, fontsize=8)
ax2.set_xticks(powersnum)
ax2.set_xticklabels(ticklabels)
plt.show()
fig1.savefig(os.path.join(savefolder,"PhasorDisplacement_absolute.pdf"))
fig2.savefig(os.path.join(savefolder,"PhasorDisplacement_normalized.pdf"))