
""" 
Plot the metrics of distances between the phasors from the .csv file generated by
PhasorDistribution_STED_EllipseFit_2Species.py
"""

import os
import glob

import numpy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn
import easygui
import itertools
from sys import path as path1; 
Functionspath=os.path.join(os.path.dirname(os.path.dirname(__file__)), "Functions")
path1.append(Functionspath)
from statistics_functions import get_significance
import scipy

matplotlib.rcParams['axes.linewidth'] = 0.8

# Ask user name of the folder where the plots will be saved and create it
savefoldername =str(input("Name of folder: "))
savefolder=os.path.join(os.path.expanduser("~/Desktop"),savefoldername + "_Simulation_Noise")
os.makedirs(savefolder,exist_ok=True)

#Path to folder containing the .csv files
csvpath = easygui.fileopenbox(default=os.path.expanduser("~/Desktop"),multiple=False)



colors=["#7ce8ffff","#55d0ffff","#00acdfff","#2895cbff","#1676a9ff","#00456bff"]

# Read the .csv files and concatenate them
cumdf=[]
csvfull=[]



Overall_data= pd.read_csv(csvpath)
print(Overall_data.shape)
print(list(Overall_data.columns))

df=Overall_data[Overall_data["Noise type"]=="Uniform"]
df=df[df["Noise number photons"]==0]

SQ1C=numpy.array(df[["squirrel_f1"]])
SQ2C=numpy.array(df[["squirrel_f2"]])
PowC=numpy.array(df[["Power"]])


types=["Uniform","IRF","Alexa647"]
fig2,ax2=plt.subplots(ncols=2,nrows=3,sharex=True,sharey=True,figsize=(27,9))
for t,type in enumerate(types):
    fig1,ax1=plt.subplots(figsize=(8,6))
    df=Overall_data[Overall_data["Noise type"]==type]
    pixels=numpy.unique(df["Noise percent pixels"])
    photons=numpy.unique(df["Noise number photons"])
    print(pixels)
    print(photons)
    if 0 in pixels:
        pixels=numpy.delete(pixels,numpy.where(pixels==0)[0][0])
    print(pixels)
    if 0 in photons:
        photons=numpy.delete(photons,numpy.where(photons==0)[0][0])
    print(photons)
   
    for i,p in enumerate(pixels):
        if p==0:
            continue
        df2=df[df["Noise percent pixels"]==p]
        ax2[t,i].errorbar(20,numpy.mean(SQ1C),yerr=numpy.std(SQ1C),c="k",fmt="o", label="Control F1",markersize=10)
        ax2[t,i].errorbar(20,numpy.mean(SQ2C),yerr=numpy.std(SQ2C),c="grey", fmt="o", label="Control F2",markersize=10)

        for j,n in enumerate(photons):

            df3=df2[df2["Noise number photons"]==n]
            #ax2[t,i].scatter(df3["Power"],df3["squirrel_f1"],c=colors[0], label="{} photons".format(n))
            #ax2[t,i].scatter(df3["Power"],df3["squirrel_f2"],c=colors[1], label="{} photons".format(n))
            ax2[t,i].errorbar(20,numpy.mean(df3["squirrel_f1"]),yerr=numpy.std(df3["squirrel_f1"]),fmt="o",c=colors[0], label="{} photons F1".format(n),markersize=10)
            ax2[t,i].errorbar(20,numpy.mean(df3["squirrel_f2"]),yerr=numpy.std(df3["squirrel_f2"]),fmt="o",c=colors[1], label="{} photons F2".format(n),markersize=10)

        ax2[t,i].set_title("{}:{}% pixels".format(type,p))
        ax2[t,i].set_xlabel("Power")
        ax2[t,i].set_ylabel("SQUIRREL")
ax2[t,i].legend(frameon=False,loc='upper right')

fig2.savefig(os.path.join(savefolder,"Triangledraw_{}.pdf".format(type)),transparent=True, bbox_inches='tight')
plt.show()
